//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaVantageConnector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AvResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaVantageConnector.Resources.AvResources", typeof(AvResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is empty..
        /// </summary>
        internal static string ApiKeyIsNullException {
            get {
                return ResourceManager.GetString("ApiKeyIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string BadRequestToken {
            get {
                return ResourceManager.GetString("BadRequestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Quote.
        /// </summary>
        internal static string GlobalQuote {
            get {
                return ResourceManager.GetString("GlobalQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect function name.
        /// </summary>
        internal static string IncorrectFunctionNameValidateError {
            get {
                return ResourceManager.GetString("IncorrectFunctionNameValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval value..
        /// </summary>
        internal static string InvalidtIntervalValueError {
            get {
                return ResourceManager.GetString("InvalidtIntervalValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data.
        /// </summary>
        internal static string MetaDataHeader {
            get {
                return ResourceManager.GetString("MetaDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword is empty..
        /// </summary>
        internal static string SymbolSearchInputEmptyEx {
            get {
                return ResourceManager.GetString("SymbolSearchInputEmptyEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Analysis.
        /// </summary>
        internal static string TechnicalAnalysis {
            get {
                return ResourceManager.GetString("TechnicalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Series.
        /// </summary>
        internal static string TimeSeries {
            get {
                return ResourceManager.GetString("TimeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown API Function..
        /// </summary>
        internal static string UnknownApiFunctionException {
            get {
                return ResourceManager.GetString("UnknownApiFunctionException", resourceCulture);
            }
        }
    }
}
